# Generated by Django 2.2.7 on 2021-01-16 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('complete_date', models.DateField(default=datetime.date.today)),
                ('subject', models.CharField(max_length=99)),
                ('detail', models.TextField(max_length=999)),
                ('status', models.CharField(choices=[('imp', 'imp'), ('regular', 'regular'), ('done', 'done')], max_length=99)),
                ('days', models.IntegerField()),
            ],
        ),
    ]
