# Generated by Django 2.2.7 on 2021-01-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='days',
        ),
    ]
