# Generated by Django 2.2.7 on 2021-01-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_tasks_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('important', 'important'), ('regular', 'regular'), ('done', 'done')], max_length=99),
        ),
    ]
